### ISSUE TITLE
New Logo Offer SuperTTTAndroid

### ISSUE THREAD

**Issue by familqasimov** [henrykvdb/UltimateTTTAndroid#5]
Hi sir. I'm graphic designer. I have studied your work and I think a new design will make you more visible. I would like to offer logo. I can give you all the formats of the design free. If you want I send you PR or a change please specify.

![super tic tac toe](https://user-images.githubusercontent.com/36432269/39490501-2435456c-4d9a-11e8-96ab-cfe34bd2929c.png)

**Comment by henrykvdb** [comment]
Thank you for the offer! I like how the logo makes it clear what the app does, while still being pretty simple. That being said, there are a couple of issues with it.

- The colors of the cross and circle are wrong. The cross should be blue (RGB 0,0,240+) and the circle should be red (RGB 240+,0,0).
- I tried this design before in paint, but could not get it to look good without looking too simular to the logo of a competitor on the Google Play store (see below). Maybe another idea for the icon would be better.
![competitor logo](https://user-images.githubusercontent.com/1943875/39551738-81ba357c-4e66-11e8-868f-51aa79054c05.png)
- I'm not a fan of the gradient on the upper part of the design, because it makes the icon more complicated then it should be.

I'm sorry for the detailed remarks, thanks a lot for your consideration.

**Comment by familqasimov** [comment]
Hello, Mr.
I hope this icon is closer to your ideals

![untitled-2](https://user-images.githubusercontent.com/36432269/39559069-987098c2-4ea4-11e8-8956-a8ae84ec1412.png)

**Comment by henrykvdb** [comment]
Hey thanks for the fixes! However I still think the design looks a little bit too similar to the one of that competitor. Could you maybe try something different or other variations of the design?

**Comment by familqasimov** [comment]
Hi friend I fixed logo this. I hope you like. 

* Icons - Style - Material Design says "Product icon design is inspired by the tactile and physical quality of material".
So, I done a shadow effect like a drop shadow on every object. (A thin line may not be necessary)

![3](https://user-images.githubusercontent.com/36432269/40086212-7a05e46e-58ae-11e8-930f-50604b9f81f1.png)

Best regards:
Famil Qasimov
